name: Docker Compose Build CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker-compose up -d --build

      - name: Tear down Docker Compose
        run: docker-compose down
