name: Node Jest Tests CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go int the app directory and install dependencies
        run: |
          cd app
          npm install

      - name: Run tests
        run: |
          cd app
          npm test
